----------CÁC CÂU QUERY----------
SELECT * FROM KHACHHANG
SELECT * FROM PHONG
SELECT * FROM LOAIPHONG
SELECT * FROM NHANVIEN
SELECT * FROM PHIEUDICHVU
SELECT * FROM DATPHONG
SELECT * FROM HOADON

--Còn bao nhiêu phòng trống
SELECT COUNT(*) AS N'SỐ LƯỢNG PHÒNG TRỐNG' FROM PHONG
WHERE TINHTRANG = 'AVAILABLE'

--Tìm tên phòng va những khách đặt vào ngày 03/01/2023
SELECT KHACHHANG.HOTENKH AS N'HỌ TÊN KHÁCH HÀNG', PHONG.TENPHONG AS N'TÊN PHÒNG', DATPHONG.NGAYTAO AS N'NGÀY ĐẶT PHÒNG' FROM DATPHONG
JOIN KHACHHANG ON DATPHONG.MAKH = KHACHHANG.MAKH
JOIN PHONG ON DATPHONG.MAPHONG = PHONG.MAPHONG
WHERE NGAYTAO = '03/01/2023'

--Tìm phòng có tên B03
SELECT * FROM PHONG 
WHERE TENPHONG ='B03'

--Phòng Superior có trang bị như thế nào
SELECT TENLOAIPHONG, TRANGBI FROM LOAIPHONG
WHERE TENLOAIPHONG = 'Superior'

--Tìm giá, số lượng và trang bị của các loại phòng Standard, Superior, Deluxe
SELECT LOAIPHONG.SOLUONG, LOAIPHONG.TENLOAIPHONG, LOAIPHONG.TRANGBI, PHONG.GIAPHONG FROM LOAIPHONG
JOIN PHONG ON LOAIPHONG.MALOAIPHONG = PHONG.MALOAIPHONG
GROUP BY SOLUONG, TENLOAIPHONG, TRANGBI, GIAPHONG

--Khách sạn bao gồm những dịch vụ nào và hiển thị giá của nó
SELECT * FROM PHIEUDICHVU

--Tìm tìm thông tin khách hàng đã đặt phòng ‘A08’ (Tên, SDT, CMND, Địa Chỉ)
SELECT KHACHHANG.HOTENKH, KHACHHANG.CMND, KHACHHANG.SDT, KHACHHANG.DCHI, PHONG.TENPHONG FROM DATPHONG
JOIN PHONG ON DATPHONG.MAPHONG = PHONG.MAPHONG
JOIN KHACHHANG ON DATPHONG.MAKH = KHACHHANG.MAKH
WHERE PHONG.TENPHONG = 'A08'

--Tìm những khách hàng sử dụng dịch vụ Thuê xe, Giặt ủi, Spa, Đặt vé, Karaoke,... và hiển thị giá của các dịch vụ đó
SELECT KHACHHANG.HOTENKH, PHIEUDICHVU.TENDICHVU, PHIEUDICHVU.GIA FROM DATPHONG
JOIN PHIEUDICHVU ON DATPHONG.MADICHVU = PHIEUDICHVU.MAPHIEUDICHVU
JOIN KHACHHANG ON DATPHONG.MAKH = KHACHHANG.MAKH

--Tìm những khách hàng đặt hơn 1 phòng (nhiều phòng)--
SELECT KHACHHANG.HOTENKH, COUNT(*) AS 'Số phòng khách đã đặt' FROM DATPHONG
JOIN KHACHHANG ON DATPHONG.MAKH = KHACHHANG.MAKH
GROUP BY KHACHHANG.HOTENKH
HAVING COUNT(*) > 1

--Tìm các khách hàng trả trước 1 triệu đồng (1000000), ngày trả trước và nhân viên nào quản lý những khách hàng đó
SELECT KHACHHANG.HOTENKH, DATPHONG.TRATRUOC AS N'SỐ TIỀN TRẢ TRƯỚC', DATPHONG.NGAYTAO AS N'NGÀY TRẢ TRƯỚC', PHONG.TENPHONG FROM DATPHONG
JOIN KHACHHANG ON DATPHONG.MAKH = KHACHHANG.MAKH
JOIN NHANVIEN ON DATPHONG.MANV = NHANVIEN.MANV
JOIN PHONG ON DATPHONG.MAPHONG = PHONG.MAPHONG
WHERE TRATRUOC = '1000000'

--Tìm khách hàng đặt phòng vào ngày 11/02/2023 (TAOPHONG), trả trước 300.000 đồng và khách hàng đó sử dụng dịch vụ gì
SELECT KHACHHANG.HOTENKH, DATPHONG.NGAYTAO AS N'NGÀY ĐẶT HÀNG', DATPHONG.TRATRUOC AS N'SỐ TIỀN TRẢ TRƯỚC', PHIEUDICHVU.TENDICHVU FROM DATPHONG
JOIN KHACHHANG ON DATPHONG.MAKH = KHACHHANG.MAKH
JOIN PHIEUDICHVU ON DATPHONG.MADICHVU = PHIEUDICHVU.MAPHIEUDICHVU
WHERE DATPHONG.NGAYTAO = '2023-02-11' AND DATPHONG.TRATRUOC = '300000'

--Tìm khách hàng đặt phòng Superior, hiển thị trang bị và giá của phòng đó
SELECT KHACHHANG.HOTENKH, LOAIPHONG.TENLOAIPHONG, LOAIPHONG.TRANGBI, PHONG.GIAPHONG FROM DATPHONG
JOIN PHONG ON PHONG.MAPHONG = DATPHONG.MAPHONG
JOIN LOAIPHONG ON PHONG.MALOAIPHONG = LOAIPHONG.MALOAIPHONG
JOIN KHACHHANG ON DATPHONG.MAKH = KHACHHANG.MAKH
WHERE PHONG.MALOAIPHONG = '992'

--Tìm những khách hàng trả phòng vào ngày 03/03/2023 và tên nhân viên quản lý khách hàng đó
SELECT KHACHHANG.HOTENKH, DATPHONG.NGAYTRAPHONG, NHANVIEN.TENNV FROM DATPHONG
JOIN KHACHHANG ON DATPHONG.MAKH = KHACHHANG.MAKH
JOIN NHANVIEN ON DATPHONG.MANV = NHANVIEN.MANV
WHERE DATPHONG.NGAYTRAPHONG = '2023-03-03'

--Khách hàng đã trả những phòng nào, đếm số lượng các phòng khách hàng đã trả và những phòng đó chuyển về trạng thái còn trống
SELECT KHACHHANG.HOTENKH,TENPHONG, COUNT(TINHTRANG) AS N'Số phòng khách đã trả' , PHONG.TINHTRANG FROM DATPHONG
JOIN PHONG ON PHONG.MAPHONG = DATPHONG.MAPHONG
JOIN LOAIPHONG ON PHONG.MALOAIPHONG = LOAIPHONG.MALOAIPHONG
JOIN KHACHHANG ON DATPHONG.MAKH = KHACHHANG.MAKH
WHERE TINHTRANG = 'AVAILABLE'
GROUP BY TENPHONG, KHACHHANG.HOTENKH, PHONG.TINHTRANG

--Lọc danh sách khách hàng đặt phòng trong quý 1 (bắt đầu từ tháng 1 đến hết tháng 3)--
SELECT KHACHHANG.HOTENKH, DATPHONG.NGAYTAO FROM DATPHONG 
JOIN KHACHHANG ON DATPHONG.MAKH = KHACHHANG.MAKH
WHERE MONTH(DATPHONG.NGAYTAO) > 1 AND MONTH(DATPHONG.NGAYTAO) <= 3

--Hiển thị chi tiết hóa đơn ‘HD10’ bao gồm tên khách hàng, nhân viên quản lý khách hàng đó, dịch vụ -- 
SELECT KHACHHANG.HOTENKH, NHANVIEN.TENNV, PHIEUDICHVU.TENDICHVU  FROM DATPHONG
JOIN KHACHHANG ON DATPHONG.MAKH = KHACHHANG.MAKH
JOIN HOADON ON DATPHONG.MAPHIEUDAT = HOADON.MAPHIEUDATPHONG
JOIN NHANVIEN ON DATPHONG.MANV = NHANVIEN.MANV
JOIN PHIEUDICHVU ON DATPHONG.MADICHVU = PHIEUDICHVU.MAPHIEUDICHVU
WHERE HOADON.MAHOADON = 'HD1'
GROUP BY KHACHHANG.HOTENKH, NHANVIEN.TENNV, PHIEUDICHVU.TENDICHVU
SELECT * FROM HOADON

--Tra cứu hóa đơn của khách hàng có thanh toán hóa đơn vào ngày 13/02/2023 bao gồm CMND, nhân viên, tổng số tiền phải trả  
SELECT KHACHHANG.HOTENKH, KHACHHANG.CMND, NHANVIEN.TENNV, HOADON.TONGSOTIENPHAITRA, HOADON.NGAYTHANHTOAN FROM DATPHONG
JOIN KHACHHANG ON DATPHONG.MAKH = DATPHONG.MAKH
JOIN PHIEUDICHVU ON DATPHONG.MADICHVU = PHIEUDICHVU.MAPHIEUDICHVU
JOIN HOADON ON DATPHONG.MAPHIEUDAT = HOADON.MAPHIEUDATPHONG
JOIN PHONG ON DATPHONG.MAPHONG = PHONG.MAPHONG
JOIN NHANVIEN ON DATPHONG.MANV = NHANVIEN.MANV
WHERE HOADON.NGAYTHANHTOAN ='2023-02-13' 
GROUP BY KHACHHANG.HOTENKH, KHACHHANG.CMND, NHANVIEN.TENNV, HOADON.TONGSOTIENPHAITRA, HOADON.NGAYTHANHTOAN
SELECT * FROM HOADON

--Hãy cho biết khách hàng có tên Phan Quốc Vinh ở bao nhiêu ngày
SELECT  DATEDIFF(day, '2023-03-01', '2023-03-04') AS N'Số ngày khách ở',KHACHHANG.HOTENKH, DATPHONG.NGAYTAO,DATPHONG.NGAYTRAPHONG FROM DATPHONG
JOIN KHACHHANG ON DATPHONG.MAKH = KHACHHANG.MAKH
WHERE DATPHONG.MAKH = '009'
GROUP BY KHACHHANG.HOTENKH, DATPHONG.NGAYTAO,DATPHONG.NGAYTRAPHONG

--Tra cứu tổng tiền hóa đơn bao gồm: tiền phòng, tiền dịch vụ, ngày thanh toán, mã nhân viên quản lý hóa đơn ‘HD6’ 
SELECT KHACHHANG.MAKH, KHACHHANG.HOTENKH, HOADON.MAHOADON,  HOADON.NGAYTHANHTOAN, HOADON.MANV,  PHONG.GIAPHONG, PHIEUDICHVU.GIA, DATPHONG.TRATRUOC, (SUM(PHIEUDICHVU.GIA)+SUM(PHONG.GIAPHONG))-DATPHONG.TRATRUOC AS N'TONG TIEN' FROM DATPHONG
JOIN KHACHHANG ON DATPHONG.MAKH = DATPHONG.MAKH
JOIN PHIEUDICHVU ON DATPHONG.MADICHVU = PHIEUDICHVU.MAPHIEUDICHVU
JOIN HOADON ON DATPHONG.MAPHIEUDAT = HOADON.MAPHIEUDATPHONG
JOIN PHONG ON DATPHONG.MAPHONG = PHONG.MAPHONG
WHERE HOADON.MAHOADON ='HD6' 
GROUP BY PHONG.GIAPHONG, PHIEUDICHVU.GIA, HOADON.NGAYTHANHTOAN, HOADON.MANV, KHACHHANG.MAKH,  HOADON.MAHOADON,KHACHHANG.HOTENKH,  DATPHONG.TRATRUOC


-- VIEW 
-- TẠO VIEW XEM NHANVIEN NÀO PHỤ TRÁCH PHIEUDATPHONG NÀO
CREATE VIEW hotel_employees AS
	SELECT TENNV, MAPHIEUDAT, NGAYTAO AS NGAYDAT, MAPHONG
	FROM NHANVIEN
	JOIN DATPHONG
	ON NHANVIEN.MANV = DATPHONG.MANV;

select * from hotel_employees

-- TẠO VIEW XEM KHACHHANG DAT PHONG NÀO VÀO NGÀY NÀO
CREATE VIEW hotel_guests AS
SELECT KHACHHANG.MAKH, HOTENKH, DCHI, GIOITINH, SDT, QUOCTICH, DATPHONG.MAPHIEUDAT, DATPHONG.NGAYTRAPHONG, DATPHONG.MAPHONG
FROM KHACHHANG
JOIN DATPHONG ON KHACHHANG.MAKH = DATPHONG.MAKH

select * from hotel_guests

-- PROCEDUCE INSERT THÔNG TIN KHÁCH HÀNG MỚI VÀO BẢNG KHÁCH HÀNG

SET IDENTITY_INSERT KHACHHANG  ON
GO
CREATE PROCEDURE PCD_insert_KHACHHANG
(
@MAKH INT,
@HOTENKH NVARCHAR(30),
@DCHI NVARCHAR(20),
@GIOITINH NVARCHAR(4),
@SDT INT, 
@CMND INT, 
@QUOCTICH NVARCHAR(20)
)
AS
BEGIN
INSERT INTO KHACHHANG
(MAKH,HOTENKH,DCHI,GIOITINH,SDT, CMND, QUOCTICH)VALUES
(@MAKH,@HOTENKH,@DCHI,@GIOITINH,@SDT, @CMND, @QUOCTICH)
END

EXEC PCD_insert_KHACHHANG 022, 'Trương Thị Anh Thư', 'Bình Định', N'Nữ', 09071110, 301828, 'Việt Nam'
EXEC PCD_insert_KHACHHANG 023, 'Lê Thị Năm', 'Bạc Liêu', N'Nữ', 06846511, 3018673, 'Việt Nam'
EXEC PCD_insert_KHACHHANG 024, 'Trần Bảo Tuyết', 'Thanh Hóa', N'Nữ', 09080700, 3067297, 'Việt Nam'
EXEC PCD_insert_KHACHHANG 025, 'Trịnh Bách Nam', 'Quảng Ninh', N'Nam', 09781117, 3018280, 'Việt Nam'
EXEC PCD_insert_KHACHHANG 026, 'Lê Tuấn Khôi', 'TP.Hồ Chí Minh', N'Nam', 09335611, 308954, 'Việt Nam'

--PROCEDURE INSERT THÔNG TIN NHÂN VIÊN MỚI VÀO BẢNG NHÂN VIÊN
CREATE PROCEDURE PCD_insert_NHANVIEN
(
@MANV INT,
@TENNV NVARCHAR(20),
@GIOITINH VARCHAR(3),
@NSINH DATE,
@SDT INT,
@DCHI NVARCHAR(20)
)
AS
BEGIN
INSERT INTO KHACHHANG(MANV,TENNV,GIOITINH,NSINH,SDT,DCHI)VALUES
(@MANV,@TENNV,@GIOITINH,@NSINH,@SDT,@DCHI)
END

EXEC PCD_insert_NHANVIEN 121, 'Nguyễn Minh Hiếu', N'Nam', '21-07-2004', 0913055119, 'An Giang'
EXEC PCD_insert_NHANVIEN 122, 'Trần Minh Giàu', N'Nam', '2001-01-19', 06784451245, 'Nghệ An'
EXEC PCD_insert_NHANVIEN 123, 'Nguyễn Khánh Duy', N'Nam', '1999-07-26', 0913654111, 'Thanh Hóa'
EXEC PCD_insert_NHANVIEN 124, 'Trần Thị Ngọc Minh', N'Nữ', '1989-08-30', 0907080044, 'Hà Nội'
EXEC PCD_insert_NHANVIEN 125, 'Nguyễn Thị Hồng Nguyên', N'Nữ', '1997-07-19', 0901323675, 'Long An' 


-- PROCEDURE QUY TRÌNH ĐẶT PHÒNG NHẬP DỮ LIỆU VÀO BẢNG DATPHONG VÀ SET TÌNH TRẠNG AVAILABLE SANG FULL
CREATE PROCEDURE PCD_DATPHONG_NHAPDULIEU
(
@MAPHIEUDAT NVARCHAR(10) ,
@MAKH INT,
@NGAYTAO DATE,
@NGAYTRAPHONG DATE,
@MAPHONG NVARCHAR(10),
@TRATRUOC INT,
@MADICHVU NVARCHAR(10),
@MANV INT
)
AS
BEGIN
INSERT INTO DATPHONG
(MAPHIEUDAT,MAKH,NGAYTAO,NGAYTRAPHONG,MAPHONG,TRATRUOC,MADICHVU,MANV) VALUES
(@MAPHIEUDAT,@MAKH,@NGAYTAO,@NGAYTRAPHONG,@MAPHONG,@TRATRUOC,@MADICHVU,@MANV)
UPDATE PHONG SET TINHTRANG='FULL' WHERE @MAPHONG=MAPHONG
END
 
EXEC PCD_DATPHONG_NHAPDULIEU 'PD13', 022,'2023-04-30','2023-05-19', '881', 200000, 'VU09', 125
EXEC PCD_DATPHONG_NHAPDULIEU 'PD14', 023, '2023-05-01', '2023-05-10', '885', 1000000, 'VU06', 121
EXEC PCD_DATPHONG_NHAPDULIEU 'PD15', 024, '2023-06-18', '2023-06-20', '901', 300000, 'VU06', 124
EXEC PCD_DATPHONG_NHAPDULIEU 'PD16', 025, '2023-05-29', '2023-06-02', '888', 500000, 'VU05', 123
EXEC PCD_DATPHONG_NHAPDULIEU 'PD17', 026, '2023-04-13', '2023-04-15', '889', 2000000, 'VU07', 122 

-- PROCEDURE THANH TOÁN HÓA ĐƠN VÀ LƯU VÔ BẢNG HÓA ĐƠN (SET TÌNH TRẠNG TỪ FULL SANG AVAILABLE
CREATE PROCEDURE HOANTAT_THANHTOAN
(
@MAHOADON NVARCHAR(10),
@MAPHONG NVARCHAR(10),
@NGAYTHANHTOAN DATE,
@SOTIENTRATRUOC INT,
@MANV INT,
@MAPHIEUDATPHONG NVARCHAR(10),
@MADICHVU NVARCHAR(10),
@TONGSOTIENPHAITRA INT 
)
AS
BEGIN
DECLARE @TONGTIEN FLOAT = (SELECT (SUM(PHIEUDICHVU.GIA)+SUM(PHONG.GIAPHONG))-DATPHONG.TRATRUOC FROM DATPHONG 
JOIN PHONG ON PHONG.MAPHONG = DATPHONG.MAPHONG 
JOIN PHIEUDICHVU ON PHIEUDICHVU.MAPHIEUDICHVU = DATPHONG.MADICHVU
WHERE DATPHONG.MAPHONG=@MAPHONG)
INSERT INTO HOADON
(MAHOADON,NGAYTHANHTOAN,SOTIENTRATRUOC,MANV,MAPHIEUDATPHONG,MADICHVU,TONGSOTIENPHAITRA)
VALUES
(@MAHOADON,@NGAYTHANHTOAN,@SOTIENTRATRUOC,@MANV,@MAPHIEUDATPHONG,@MADICHVU,@TONGSOTIENPHAITRA)
UPDATE PHONG SET TINHTRANG='AVAILABLE' WHERE @MAPHONG=MAPHONG
END

EXEC HOANTAT_THANHTOAN 'HD13', '881', '2023-05-19', 200000, 125, 'VU09', 'PD13', 610000
EXEC HOANTAT_THANHTOAN 'HD14', '885', '2023-05-10', 1000000, 121, 'PD14', 'VU06', 850000
EXEC HOANTAT_THANHTOAN 'HD15', '901', '2023-06-20', 300000, 124, 'PD15', 'VU06', 3100000
EXEC HOANTAT_THANHTOAN 'HD16', '888', '2023-06-02', 500000, 123, 'PD16', 'VU05', 860000
EXEC HOANTAT_THANHTOAN 'HD17', '889', '2023-04-15', 500000, 122, 'PD17', 'VU07', 870000